<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://example.com">
  <wsdl:types>
    <xsd:schema targetNamespace="http://site.example/ws/spec">
      <xsd:include schemaLocation="/xsd/simple_element.xsd"/>
    </xsd:schema>
  </wsdl:types>
</wsdl:definitions>
