version: 2
formats: all
build:
  os: ubuntu-20.04
  tools:
    python: '3.10'
python:
  install:
  - requirements: docs/requirements.txt
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
